### ISSUE TITLE
[レビュー申請]Vagrantを用いた汎用的なOS開発環境の構築

### ISSUE THREAD

**Issue by liva** [osdev-jp/core-members#2]
申請者：Liva
URL: https://github.com/osdev-jp/core-members/blob/master/wiki/2016/vagrant.md

**Comment by liva** [comment]
OS開発環境構築とか関係ない、ただのVagrantの記事になった

**Comment by hikalium** [comment]
bootstrap.shの内容例を記述した方がよいのでは？これでは本当にただVagrantの使い方記事になってしまいます。

**Comment by liva** [comment]
でもbootstrap.shって、apt-get install -y g++とかしてるだけなんですよね。。。うーん。。。

それこそ、Vagrantの使い方記事でも良いかもしれません。OS開発環境構築が混ざると、特定のOS開発環境にfixした記事になってしまうので。

**Comment by liva** [comment]
Vagrantの使い方記事でも良い気がしてきた。OS開発環境構築が混ざると、特定のOS開発環境にfixした記事になってしまうので。

**Comment by uchan-nos** [comment]
まず、この記事の想定読者を確認させてください。楽して環境構築したい人なのか、俺の作った最強の環境レシピを配布したい人なのか。想定読者が決まったら、記事の上の方に明記してください。

私の解釈では、この記事を読む層は、独自のプロビジョニングレシピを作って複数のマシンに開発環境を作りたいなあ、という人よりも、良い感じのプロビジョニングファイルをゲットしてサクッと開発環境を作りたい、という人が多いと予想します。

「こうするだけで、一回しか実行されない環境構築シェルスクリプトの完成です。」をネタで言っているのかもしれませんが、一回しか実行されないなら自動化する意味はそもそもないわけで、手動構築すればいいのです。対象読者が後者だとすると、「プロビジョニングレシピの作成」の節はごっそりいらなくなり、代わりに「プロビジョニングレシピの取得と利用」みたいな節がほしくなります。

> そこで登場するのがVagrantです。VagrantはVirtualBoxのラッパーみたいな物で、ターミナルからvagrantコマンドを叩くと裏でVirtualBox仮想マシンを立ち上げ、そこにssh接続をしてくれます。

意図的にこう書いているのだと思いますが、この用途にVagrantは必須ではないですよね。だから、まずは「GUIは重くて使いにくいので、CUIで仮想環境を作ってそのにSSHして開発すると良い。それを自力でやってもいいが、Vagrantを使うと自動的にその環境を作ってくれる」という論理の流れが良いと思います。

> ssh接続、つまりCUIベースなので、カクついたりするストレスもありません。世の中便利になったものです。

これはVMが出る前からの手法なわけで、世の中便利になったというより、昔の技術も捨てたもんじゃない、という感じかと。

> 次に、Vagrantfileと呼ばれるファイルを作ります。ターミナルで以下のコマンドを実行してみてください。

Mac か何か、bash っぽいシェルがあることが前提のようですが、記事のここまでの部分にはホストが Windows なのか Mac なのか記載されていませんので、ちょっと不親切です。私は Windows を無意識に想定して読んでいて、いきなり `$` が出てきてびっくりしました。「Mac の場合は次のコマンドです」「Windows の場合については加筆してくださる方を募集しています」などと書きませんか？

> 一般的にOS開発はLinuxを使うのが一番簡単なので

本当に一般的にそう思われているのでしょうか。tolsetの枠内で収まる範囲ならWindowsが一番楽と思う人も多いのでは？ここは「ちょっと高度なOS開発をしようとするとLinuxがいろいろ便利なので」とか、そういう感じがいいです。（livaさんも多分そういうことが言いたかったのではないでしょうか）

> このVagrantfileはubuntu14.04ベースの仮想マシンを作ってくれます。

記事の中で「ubuntu」と「Ubuntu」が表記ゆれしているので統一しましょう。（centosも大文字・小文字を直したいです。）

> 次にqemuのコンソールでvncのパスワードを設定します。

qemu を起動するたびに毎回パスワード設定が必要ですか？その場合、なんとか改善する方法を見つけて記事に追加してもらえないでしょうか。

VNC について詳しくない人もいると思いますから、どこか詳しい説明にリンクを張っておくと良いです。

また、VNC でやる他に X11 転送でやる方法もある旨を記載しておくと親切でしょう。Vagrant で入る Ubuntu 14.,04 が Server 版（CUI のみのやつ）だと X11 クライアントなど入ってないはずなので、その注意書きも必要ですが。動作検証するのが億劫なら、「X11 転送でやる方法もあるようですが、ここでは触れません」という感じでもいいです。

**Comment by liva** [comment]
> 私の解釈では、この記事を読む層は、独自のプロビジョニングレシピを作って複数のマシンに開発環境を作りたいなあ、という人よりも、良い感じのプロビジョニングファイルをゲットしてサクッと開発環境を作りたい、という人が多いと予想します。

osdev-jpオープンコミュニティであれば、良い感じのプロビジョニングファイルを使って手抜き開発環境を、という話になるかもしれませんが、WordPress記事となると、ある程度独自でいろいろやってる層向けで書いて良いと思います。
確かに層としては、高度な技術を持ってる人よりも入門者の方が多いのはその通りですが、コアメンバーが提供する記事というのは、コアメンバーにしか書けないレベルの高い記事であるべき（これがそもそもの目的ですよね？）で、その記事が対象とする読者は、独自のプロビジョニングレシピを作る人達なのではないかと思います。

良い感じのプロビジョニングファイルは、書きたい人がオープンコミュニティに置いておけば良いのではないでしょうか？

> 「GUIは重くて使いにくいので、CUIで仮想環境を作ってそのにSSHして開発すると良い。それを自力でやってもいいが、Vagrantを使うと自動的にその環境を作ってくれる」という論理の流れが良い

確かに、Vagrantの優位性である「手軽さ」という部分にあまりフォーカスできていませんね。加筆しておきます。

> 「Mac の場合は次のコマンドです」「Windows の場合については加筆してくださる方を募集しています」などと書きませんか？

なるほど、コマンド自体はどの環境でも同じなのですが、UNIX環境である事は明記すべきですね。

> ここは「ちょっと高度なOS開発をしようとするとLinuxがいろいろ便利なので」とか、そういう感じがいいです。

これもなるほどその通りです。

> 記事の中で「ubuntu」と「Ubuntu」が表記ゆれしているので統一しましょう。

あちゃー、直します

>  qemu を起動するたびに毎回パスワード設定が必要ですか？その場合、なんとか改善する方法を見つけて記事に追加してもらえないでしょうか。

残念なことにqemu側にパスワードを事前に設定するインターフェースがありません。根本的に改善するなら、vnc以外を使うしかないでしょうね。。。
別の選択肢として、共有フォルダでホストにディスクイメージを飛ばす部分についても書いておきます。

> また、VNC でやる他に X11 転送でやる方法もある旨を記載しておくと親切でしょう。

X11使う方法は今知りました(笑)
一言書いておきます。

**Comment by uchan-nos** [comment]
@liva 

> 確かに層としては、高度な技術を持ってる人よりも入門者の方が多いのはその通りですが、コアメンバーが提供する記事というのは、コアメンバーにしか書けないレベルの高い記事であるべき（これがそもそもの目的ですよね？）で、その記事が対象とする読者は、独自のプロビジョニングレシピを作る人達なのではないかと思います。

なるほど。分かりました。ではこの記事は、レシピを独自に作りたい人向けということなので、「対象読者」みたいな項目を書いていただけるとより良い記事になると思います！
そして、最後に「ちなみに、これが私が使っているレシピです。どうぞご利用ください」てな感じで書いておくと、両方の層にアプローチできます。

「コアメンバーにしか書けないレベルの高い記事」を目指すのは同意です！そして、レベルが高いというのは、技術的に高度な内容も含まれるというのももちろんですが、 **誰が読んでも満足できる** ものだと、私は思います。高度な内容だけを追求して初心者を寄せ付けない記事は、コアメンバーにしか書けないかもしれませんが「レベルが高い」とは思いません。（みなさんの解釈がこれと違っていたら教えてください）

実際には「誰が読んでも」は実現が難しいので（例えば料理のレシピを探している人には絶対に向かない）、次善策として対象読者を明記しておくのが良いということになります。また、ちょっとした工夫で読者層を広げられるならそうしたいと思っています。読者層を広げることが記事のまとまりを悪くするなら、対象読者を絞り込んだ上で尖った記事にします。

**Comment by liva** [comment]
@uchan-nos 

> 「対象読者」みたいな項目を書いていただけるとより良い記事になると思います！

この記事に限らず、全てのWordPress記事には対象読者等の情報を書く欄を作っても良さそうです。
osdev.orgだと難易度とかが書かれてたりするので、それと似たような感じで。

> ちょっとした工夫で読者層を広げられるならそうしたいと思っています。

それでいうと、WordPress記事には尖った事を書いておいて、それを読んだメンバーがオープンコミュニティに初心者向けの（例えば今回の記事であれば、Vagrantを用いたtolset構築記事とか）記事を作ると思うので、そこに対してリンクを貼っていけば良いと思います。

私達はWordPress記事について議論し過ぎて、WordPress記事にしか焦点を当てすぎるような気がするのですが（勘違いかも？）、まずosdev-jpというオープンコミュニティとWikiがあって、その中の一部門としてコアメンバーによるWordPress記事があると考えると、WordPress記事はある程度尖らせておいて、様々な読者層向けのコンテンツはオープンコミュニティに置けば良いと思います。その方が皆でいろいろ修正し合って、より良い物にしていけますからね。

**Comment by liva** [comment]
@hikalium 
サンプルコードをオープンコミュニティ記事の中に置く事にしたので、そこに誘導する形であればOS開発環境構築記事と名乗れると思います。

**Comment by hikalium** [comment]
@liva
そうですね、私は環境構築コード自体のほうが需要が高いと考えますので、bootstrap.shへのリンクが含まれることはとてもよいことだと思います。

**Comment by uchan-nos** [comment]
@liva

https://github.com/osdev-jp/core-members/commit/54154bdda6591c7c0f48012e8cc7d4c18e512f78#commitcomment-17035480
コミットに直接コメントさせていただきました！

**Comment by liva** [comment]
@uchan-nos  pushしました！

**Comment by uchan-nos** [comment]
LGTM!

**Comment by liva** [comment]
公開しました。
https://osdevjp.wordpress.com/2016/04/15/vagrant/
