### ISSUE TITLE
[レビュー申請]Visual Studio Code で OS 開発をする

### ISSUE THREAD

**Issue by uchan-nos** [osdev-jp/core-members#4]
申請者: uchan
対象: https://github.com/osdev-jp/core-members/pull/3/files

プルリクにしてみたので、レビューコメントをそちらに書いていただけると私もレビュワーも楽かなーと思います。

**Comment by liva** [comment]
遅くなりましたが、コメントしました！

**Comment by uchan-nos** [comment]
@liva @hikalium レビューを適用しました。いかがでしょう。
